# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: default.storage
    # default loader to use for all filter sets
    data_loader: flysystem_loader

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: default.storage
                cache_prefix: media/cache
                root_url: '%app.upload_path%'
    #default cache resolver for saving thumbnails
    cache: flysystem_resolver

    filter_sets:
        # the name of the "filter set"
        png:
            format: png
            # list of transformations to apply (the "filters")
            filters:
            post_processors:
                optipng: { strip_all: true, level: 5 }
        jpg:
            format: jpg
            filters:
            post_processors:
                jpegoptim: { strip_all: true, max: 70, progressive: true }
