#this is for local development
version: '3.8'
volumes:
  pgdata:
services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: base
    ports:
      - ${FPM_PORT}:9000
    volumes:
      - ./:/var/www/erp
    depends_on:
      - postgres
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/var/www/erp
    depends_on:
      - php
    restart: unless-stopped
  composer:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: composer
    command: [ 'php', '-d', ' memory_limit=-1', '/usr/bin/composer', 'install' ]
    volumes:
      - ./:/var/www/erp
#  node:
#    build:
#      context: .
#      dockerfile: docker/node/Dockerfile
#    command: sh -c "npm install"
#    volumes:
#      - ./:/var/www/erp
