const PRODUCT_STATUS_DRAFTED = 'drafted'
const PRODUCT_STATUS_ACTIVE  = 'active'
const PRODUCT_STATUS_ORDERED = 'ordered'

const STATUSES = [
  PRODUCT_STATUS_DRAFTED,
  PRODUCT_STATUS_ACTIVE,
  PRODUCT_STATUS_ORDERED,
]