version: '3.7'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  php:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    restart: always #change with unless-stopped
    volumes:
      - ../:/var/www/erp
    depends_on:
      - postgres
  nginx:
    image: nginx:1.19-alpine
    restart: always
    volumes:
      - ../:/var/www/erp
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
volumes:
  pgdata:
