const getters = {
  getId: (state) => state.entity.id,
  getTitle: (state) => state.entity.title,
  getDescription: (state) => state.entity.description,
  getOriginalPrice: (state) => state.entity.originalPrice,
  getReducedPrice: (state) => state.entity.reducedPrice,
  getDiscount: (state) => state.entity.discount,
  getSku: (state) => state.entity.sku,
  getBarcode: (state) => state.entity.barcode,
  getIsTrackQuantity: (state) => state.entity.isTrackQuantity,
  getIsContinueSellingOutOfStock: (state) => state.entity.isContinueSellingOutOfStock,
  getQuantity: (state) => state.entity.quantity,
  getIsPhysicalProduct: (state) => state.entity.isPhysicalProduct,
  getWeight: (state) => state.entity.weight,
  getHasVariants: (state) => state.entity.hasVariants,
  getIsPublic: (state) => state.entity.isPublic,
  getStatus: (state) => state.entity.status,
  getVendor: (state) => state.entity.vendor,
  getCategories: (state) => state.entity.categories,
  getTags: (state) => state.entity.tags,
  getProductFiles: (state) => state.entity.productFiles,
  getProduct: (state) => state.entity,
  getFiles: (state) => state.files,
  getVariantOptions: (state) => state.variantOptions,
  getStatusOptions: (state) => state.statusOptions,
  getVendorOptions: (state) => state.vendorOptions,
  getCategoryOptions: (state) => state.categoryOptions,
  getTagOptions: (state) => state.tagOptions,
}

export default getters