const getters = {
  getTitle: (state) => state.title,
  getDescription: (state) => state.description,
  getFiles: (state) => state.files,
  getOriginalPrice: (state) => state.originalPrice,
  getReducedPrice: (state) => state.reducedPrice,
  getDiscount: (state) => state.discount,
  getSku: (state) => state.sku,
  getBarcode: (state) => state.barcode,
  getIsTrackQuantity: (state) => state.isTrackQuantity,
  getIsContinueSellingOutOfStock: (state) => state.isContinueSellingOutOfStock,
  getQuantity: (state) => state.quantity,
  getIsPhysicalProduct: (state) => state.isPhysicalProduct,
  getWeight: (state) => state.weight,
  getHasVariants: (state) => state.hasVariants,
  getVariantOptions: (state) => state.variantOptions,
  getIsPublic: (state) => state.isPublic,
  getStatusOptions: (state) => state.statusOptions,
  getStatus: (state) => state.status,
  getVendorOptions: (state) => state.vendorOptions,
  getVendor: (state) => state.vendor,
  getCategoryOptions: (state) => state.categoryOptions,
  getCategories: (state) => state.categories,
  getTagOptions: (state) => state.tagOptions,
  getTags: (state) => state.tags,
  getProducts: (state) => state.products,
  getTotalProducts: (state) => state.totalProducts,
}

export default getters