const mutations = {
  setTitle: (state, value) => state.title = value,
  setDescription: (state, value) => state.description = value,
  setOriginalPrice: (state, value) => state.originalPrice = value,
  setReducedPrice: (state, value) => state.reducedPrice = value,
  setDiscount: (state, value) => state.discount = value,
  setSku: (state, value) => state.sku = value,
  setBarcode: (state, value) => state.barcode = value,
  setIsTrackQuantity: (state, value) => state.isTrackQuantity = value,
  setIsContinueSellingOutOfStock: (state, value) => state.isContinueSellingOutOfStock = value,
  setQuantity: (state, value) => state.quantity = value,
  setIsPhysicalProduct: (state, value) => state.isPhysicalProduct = value,
  setWeight: (state, value) => state.weight = value,
  setHasVariants: (state, value) => state.hasVariants = value,
  setVariantOptions: (state, value) => state.variantOptions = value,
  setIsPublic: (state, value) => state.isPublic = value,
  setStatusOptions: (state, value) => state.statusOptions = value,
  setStatus: (state, value) => state.status = value,
  setVendorOptions: (state, value) => state.vendorOptions = value,
  setVendor: (state, value) => state.vendor = value,
  setCategoryOptions: (state, value) => state.categoryOptions = value,
  setCategories: (state, value) => state.categories = value,
  setTagOptions: (state, value) => state.tagOptions = value,
  setTags: (state, value) => state.tags = value,
  setProducts: (state, value) => state.products = value,
  setTotalProducts: (state, value) => state.totalProducts = value,
}


export default mutations