const state = () => ({
  title: '',
  description: '',
  originalPrice: '0',
  reducedPrice: '0',
  discount: 0,
  sku: '',
  barcode: '',
  isTrackQuantity: true,
  isContinueSellingOutOfStock: false,
  quantity: 0,
  isPhysicalProduct: true,
  weight: 0,
  hasVariants: false,
  variantOptions: [],
  variants: [],
  isPublic: true,
  statusOptions: [],
  status: '/api/lookup_product_statuses/1',
  vendorOptions: [],
  vendor: '/api/vendors/1',
  categoryOptions: [],
  categories: [],
  tagOptions: [],
  tags: [],
  files: [],
  products: [],
})

export default state
